/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v10.0
processor: MIMXRT1052xxxxB
package_id: MIMXRT1052DVL6B
mcu_data: ksdk2_0
processor_version: 10.0.0
pin_labels:
- {pin_num: J1, pin_signal: GPIO_SD_B0_02, label: SDHC_D0, identifier: SDHC_D0}
- {pin_num: K1, pin_signal: GPIO_SD_B0_03, label: SDHC_D1, identifier: SDHC_D1}
- {pin_num: H2, pin_signal: GPIO_SD_B0_04, label: SDHC_D2, identifier: SDHC_D2}
- {pin_num: J2, pin_signal: GPIO_SD_B0_05, label: SDHC_D3, identifier: SDHC_D3}
- {pin_num: P2, pin_signal: GPIO_SD_B1_04, label: I2C1_SCL, identifier: I2C1_SCL;IMU_SCL;TCS_SCL;SCCB_SCL}
- {pin_num: J3, pin_signal: GPIO_SD_B0_01, label: SDHC_CLK, identifier: SDHC_CLK}
- {pin_num: J4, pin_signal: GPIO_SD_B0_00, label: SDHC_CMD, identifier: SDHC_CMD}
- {pin_num: L5, pin_signal: GPIO_SD_B1_00, label: UART4_TX, identifier: UART4_TX;WLAN_TX}
- {pin_num: M5, pin_signal: GPIO_SD_B1_01, label: UART4_RX, identifier: UART4_RX;WLAN_RX}
- {pin_num: A8, pin_signal: GPIO_B0_06, label: PWM2_A0, identifier: PWM2_A0;MOTOR_LA}
- {pin_num: A9, pin_signal: GPIO_B0_07, label: PWM2_B0, identifier: PWM2_B0;MOTOR_LB}
- {pin_num: B9, pin_signal: GPIO_B0_08, label: PWM2_A1, identifier: PWM2_A1;MOTOR_RB}
- {pin_num: C9, pin_signal: GPIO_B0_09, label: PWM2_B1, identifier: PWM2_B1;MOTOR_RA}
- {pin_num: D9, pin_signal: GPIO_B0_10, label: PWM2_A2, identifier: PWM2_A2;SERVO_B}
- {pin_num: A10, pin_signal: GPIO_B0_11, label: PWM2_B2, identifier: PWM2_B2;SERVO_F}
- {pin_num: D13, pin_signal: GPIO_B1_12, label: UART5_TX, identifier: UART5_TX;KV58_TX}
- {pin_num: D14, pin_signal: GPIO_B1_13, label: UART5_RX, identifier: UART5_RX;KV58_RX}
- {pin_num: B14, pin_signal: GPIO_B1_15, label: PWM4_A3, identifier: PWM4_A3}
- {pin_num: C14, pin_signal: GPIO_B1_14, label: PWM4_B3, identifier: PWM4_A2}
- {pin_num: K14, pin_signal: GPIO_AD_B0_12, label: UART1_TX, identifier: UART1_TX;DBG_TX}
- {pin_num: L14, pin_signal: GPIO_AD_B0_13, label: UART1_RX, identifier: UART1_RX;DBG_RX}
- {pin_num: C13, pin_signal: GPIO_B1_11, label: KEY_BTUP, identifier: KEY_BTUP}
- {pin_num: B13, pin_signal: GPIO_B1_10, label: KEY_BTOK, identifier: KEY_BTOK}
- {pin_num: A13, pin_signal: GPIO_B1_09, label: KEY_BTLF, identifier: KEY_BTLF}
- {pin_num: A12, pin_signal: GPIO_B1_08, label: KEY_BTRT, identifier: KEY_BTRT}
- {pin_num: B12, pin_signal: GPIO_B1_07, label: KEY_BTDN, identifier: KEY_BTDN}
- {pin_num: C12, pin_signal: GPIO_B1_06, label: BEEP_EN, identifier: BEEP_EN}
- {pin_num: D12, pin_signal: GPIO_B1_05, label: SERVO_EN, identifier: SERVO_EN}
- {pin_num: E12, pin_signal: GPIO_B1_04, label: KEY_BTSE, identifier: KEY_BTSE}
- {pin_num: D11, pin_signal: GPIO_B1_03, label: SERVO_FLT, identifier: SERVO_FLT}
- {pin_num: C11, pin_signal: GPIO_B1_02, label: MOTOR_EN, identifier: MOTOR_EN}
- {pin_num: B11, pin_signal: GPIO_B1_01, label: KEY_BTME, identifier: KEY_BTME}
- {pin_num: A11, pin_signal: GPIO_B1_00, label: MOTOR_FLT, identifier: MOTOR_FLT}
- {pin_num: E11, pin_signal: GPIO_B0_15, label: TOF0_XHT, identifier: TOF0_XHT}
- {pin_num: E10, pin_signal: GPIO_B0_14, label: TOF0_INT, identifier: TOF0_INT}
- {pin_num: D10, pin_signal: GPIO_B0_13, label: TOF1_XHT, identifier: TOF1_XHT}
- {pin_num: C10, pin_signal: GPIO_B0_12, label: TOF1_INT, identifier: TOF1_INT}
- {pin_num: B8, pin_signal: GPIO_B0_05, label: I2C2_SDA, identifier: I2C2_SDA;TOFn_SDA}
- {pin_num: C8, pin_signal: GPIO_B0_04, label: I2C2_SCL, identifier: I2C2_SCL;TOFn_SCL}
- {pin_num: D8, pin_signal: GPIO_B0_03, label: SPI4_SCK, identifier: SPI4_SCK;DISP_SCK}
- {pin_num: E8, pin_signal: GPIO_B0_02, label: SPI4_SDO, identifier: SPI4_SDO;DISP_SDO}
- {pin_num: E7, pin_signal: GPIO_B0_01, label: DISP_BKL, identifier: DISP_BKL}
- {pin_num: D7, pin_signal: GPIO_B0_00, label: DISP_D_C, identifier: DISP_D_C}
- {pin_num: C7, pin_signal: GPIO_EMC_41, label: DISP_RST, identifier: DISP_RST}
- {pin_num: N3, pin_signal: GPIO_SD_B1_05, label: I2C1_SDA, identifier: I2C1_SDA;IMU_SDA;TCS_SDA;SCCB_SDA}
- {pin_num: L12, pin_signal: GPIO_AD_B1_04, label: CAM_PCLK, identifier: CAM_PCLK}
- {pin_num: K12, pin_signal: GPIO_AD_B1_05, label: CAM_XCLK, identifier: CAM_XCLK}
- {pin_num: J12, pin_signal: GPIO_AD_B1_06, label: CAM_VSNC, identifier: CAM_VSNC}
- {pin_num: K10, pin_signal: GPIO_AD_B1_07, label: CAM_HREF, identifier: CAM_HREF}
- {pin_num: H13, pin_signal: GPIO_AD_B1_08, label: CAM_D9, identifier: CAM_D9}
- {pin_num: M13, pin_signal: GPIO_AD_B1_09, label: CAM_D8, identifier: CAM_D8}
- {pin_num: L13, pin_signal: GPIO_AD_B1_10, label: CAM_D7, identifier: CAM_D7}
- {pin_num: J13, pin_signal: GPIO_AD_B1_11, label: CAM_D6, identifier: CAM_D6}
- {pin_num: H12, pin_signal: GPIO_AD_B1_12, label: CAM_D5, identifier: CAM_D5}
- {pin_num: H11, pin_signal: GPIO_AD_B1_13, label: CAM_D4, identifier: CAM_D4}
- {pin_num: G12, pin_signal: GPIO_AD_B1_14, label: CAM_D3, identifier: CAM_D3}
- {pin_num: J14, pin_signal: GPIO_AD_B1_15, label: CAM_D2, identifier: CAM_D2}
- {pin_num: M12, pin_signal: GPIO_AD_B1_03, label: CAM_RST, identifier: CAM_RST}
- {pin_num: L11, pin_signal: GPIO_AD_B1_02, label: MOTOR_IR, identifier: MOTOR_IR}
- {pin_num: K11, pin_signal: GPIO_AD_B1_01, label: VOLT_BAT, identifier: VOLT_BATT}
- {pin_num: J11, pin_signal: GPIO_AD_B1_00, label: MOTOR_IL, identifier: MOTOR_IL}
- {pin_num: L10, pin_signal: GPIO_AD_B0_15, label: SERVO_IB, identifier: SERVO_IB}
- {pin_num: H14, pin_signal: GPIO_AD_B0_14, label: SERVO_IF, identifier: SERVO_IF}
- {pin_num: G10, pin_signal: GPIO_AD_B0_11, label: ENCO_RA, identifier: ENC_RA}
- {pin_num: G13, pin_signal: GPIO_AD_B0_10, label: ENC_RB, identifier: ENC_RB}
- {pin_num: F14, pin_signal: GPIO_AD_B0_09, label: ENC_LB, identifier: ENC_LB}
- {pin_num: F13, pin_signal: GPIO_AD_B0_08, label: ENC_LA, identifier: ENC_LA}
- {pin_num: F12, pin_signal: GPIO_AD_B0_07, label: SWCLK, identifier: SWCLK}
- {pin_num: E14, pin_signal: GPIO_AD_B0_06, label: SWDIO, identifier: SWDIO}
- {pin_num: G14, pin_signal: GPIO_AD_B0_05, label: BOOT_SEL1, identifier: BOOT_SEL1}
- {pin_num: F11, pin_signal: GPIO_AD_B0_04, label: BOOT_SEL0, identifier: BOOT_SEL0}
- {pin_num: G11, pin_signal: GPIO_AD_B0_03, label: LED_USR, identifier: LED_USR}
- {pin_num: M11, pin_signal: GPIO_AD_B0_02, label: LED_BUSG, identifier: LED_BUSG}
- {pin_num: H10, pin_signal: GPIO_AD_B0_01, label: KEY_BTUR, identifier: KEY_BTUS}
- {pin_num: M14, pin_signal: GPIO_AD_B0_00, label: LED_BUSR, identifier: LED_BUSR}
- {pin_num: M3, pin_signal: GPIO_SD_B1_02, label: TCS_INT, identifier: TCS_INT}
- {pin_num: M4, pin_signal: GPIO_SD_B1_03, label: IMU_INT, identifier: IMU_INT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_xbara.h"
#include "fsl_xbarb.h"
#include "fsl_iomuxc.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RTEPIN_AllPin:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: C13, peripheral: GPIO2, signal: 'gpio_io, 27', pin_signal: GPIO_B1_11, direction: INPUT, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_22K_Ohm,
    pull_keeper_select: Pull}
  - {pin_num: A13, peripheral: GPIO2, signal: 'gpio_io, 25', pin_signal: GPIO_B1_09, direction: INPUT, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_22K_Ohm,
    pull_keeper_select: Pull}
  - {pin_num: B13, peripheral: GPIO2, signal: 'gpio_io, 26', pin_signal: GPIO_B1_10, direction: INPUT, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_22K_Ohm,
    pull_keeper_select: Pull}
  - {pin_num: A12, peripheral: GPIO2, signal: 'gpio_io, 24', pin_signal: GPIO_B1_08, direction: INPUT, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_22K_Ohm,
    pull_keeper_select: Pull}
  - {pin_num: B12, peripheral: GPIO2, signal: 'gpio_io, 23', pin_signal: GPIO_B1_07, direction: INPUT, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_22K_Ohm,
    pull_keeper_select: Pull}
  - {pin_num: C12, peripheral: GPIO2, signal: 'gpio_io, 22', pin_signal: GPIO_B1_06, direction: OUTPUT}
  - {pin_num: D12, peripheral: GPIO2, signal: 'gpio_io, 21', pin_signal: GPIO_B1_05, direction: OUTPUT, gpio_init_state: 'false', drive_strength: R0}
  - {pin_num: E12, peripheral: GPIO2, signal: 'gpio_io, 20', pin_signal: GPIO_B1_04, direction: INPUT, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_22K_Ohm,
    pull_keeper_select: Pull}
  - {pin_num: C11, peripheral: GPIO2, signal: 'gpio_io, 18', pin_signal: GPIO_B1_02, direction: OUTPUT, gpio_init_state: 'false', drive_strength: R0}
  - {pin_num: B11, peripheral: GPIO2, signal: 'gpio_io, 17', pin_signal: GPIO_B1_01, direction: INPUT, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_22K_Ohm,
    pull_keeper_select: Pull}
  - {pin_num: E11, peripheral: GPIO2, signal: 'gpio_io, 15', pin_signal: GPIO_B0_15, direction: OUTPUT}
  - {pin_num: E10, peripheral: GPIO2, signal: 'gpio_io, 14', pin_signal: GPIO_B0_14, direction: INPUT}
  - {pin_num: D10, peripheral: GPIO2, signal: 'gpio_io, 13', pin_signal: GPIO_B0_13, direction: OUTPUT}
  - {pin_num: C10, peripheral: GPIO2, signal: 'gpio_io, 12', pin_signal: GPIO_B0_12, direction: INPUT}
  - {pin_num: A10, peripheral: PWM2, signal: 'B, 2', pin_signal: GPIO_B0_11, identifier: PWM2_B2, direction: OUTPUT}
  - {pin_num: D9, peripheral: PWM2, signal: 'A, 2', pin_signal: GPIO_B0_10, identifier: PWM2_A2, direction: OUTPUT}
  - {pin_num: C9, peripheral: PWM2, signal: 'B, 1', pin_signal: GPIO_B0_09, identifier: PWM2_B1, direction: OUTPUT}
  - {pin_num: A9, peripheral: PWM2, signal: 'B, 0', pin_signal: GPIO_B0_07, identifier: PWM2_B0, direction: OUTPUT}
  - {pin_num: A8, peripheral: PWM2, signal: 'A, 0', pin_signal: GPIO_B0_06, identifier: PWM2_A0, direction: OUTPUT}
  - {pin_num: B8, peripheral: LPI2C2, signal: SDA, pin_signal: GPIO_B0_05, identifier: I2C2_SDA}
  - {pin_num: C8, peripheral: LPI2C2, signal: SCL, pin_signal: GPIO_B0_04, identifier: I2C2_SCL}
  - {pin_num: D8, peripheral: LPSPI4, signal: SCK, pin_signal: GPIO_B0_03, identifier: SPI4_SCK, direction: OUTPUT, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: E8, peripheral: LPSPI4, signal: SDO, pin_signal: GPIO_B0_02, identifier: SPI4_SDO, direction: OUTPUT, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: E7, peripheral: GPIO2, signal: 'gpio_io, 01', pin_signal: GPIO_B0_01, direction: OUTPUT, slew_rate: Fast}
  - {pin_num: D7, peripheral: GPIO2, signal: 'gpio_io, 00', pin_signal: GPIO_B0_00, direction: OUTPUT, slew_rate: Fast}
  - {pin_num: D13, peripheral: LPUART5, signal: TX, pin_signal: GPIO_B1_12, identifier: UART5_TX, slew_rate: Fast}
  - {pin_num: D14, peripheral: LPUART5, signal: RX, pin_signal: GPIO_B1_13, identifier: UART5_RX, slew_rate: Fast}
  - {pin_num: B14, peripheral: PWM4, signal: 'A, 3', pin_signal: GPIO_B1_15, direction: OUTPUT}
  - {pin_num: C14, peripheral: PWM4, signal: 'A, 2', pin_signal: GPIO_B1_14, direction: OUTPUT}
  - {pin_num: A7, peripheral: GPIO3, signal: 'gpio_io, 26', pin_signal: GPIO_EMC_40}
  - {pin_num: C7, peripheral: GPIO3, signal: 'gpio_io, 27', pin_signal: GPIO_EMC_41, direction: OUTPUT, slew_rate: Fast}
  - {pin_num: J4, peripheral: USDHC1, signal: usdhc_cmd, pin_signal: GPIO_SD_B0_00, slew_rate: Fast}
  - {pin_num: J3, peripheral: USDHC1, signal: usdhc_clk, pin_signal: GPIO_SD_B0_01, slew_rate: Fast}
  - {pin_num: J1, peripheral: USDHC1, signal: 'usdhc_data, 0', pin_signal: GPIO_SD_B0_02, slew_rate: Fast}
  - {pin_num: K1, peripheral: USDHC1, signal: 'usdhc_data, 1', pin_signal: GPIO_SD_B0_03, slew_rate: Fast}
  - {pin_num: H2, peripheral: USDHC1, signal: 'usdhc_data, 2', pin_signal: GPIO_SD_B0_04, slew_rate: Fast}
  - {pin_num: J2, peripheral: USDHC1, signal: 'usdhc_data, 3', pin_signal: GPIO_SD_B0_05, slew_rate: Fast}
  - {pin_num: L5, peripheral: LPUART4, signal: TX, pin_signal: GPIO_SD_B1_00, identifier: UART4_TX, slew_rate: Fast}
  - {pin_num: M5, peripheral: LPUART4, signal: RX, pin_signal: GPIO_SD_B1_01, identifier: UART4_RX, slew_rate: Fast}
  - {pin_num: M3, peripheral: GPIO3, signal: 'gpio_io, 02', pin_signal: GPIO_SD_B1_02, direction: INPUT}
  - {pin_num: M4, peripheral: GPIO3, signal: 'gpio_io, 03', pin_signal: GPIO_SD_B1_03, direction: INPUT}
  - {pin_num: P2, peripheral: LPI2C1, signal: SCL, pin_signal: GPIO_SD_B1_04, identifier: I2C1_SCL}
  - {pin_num: N3, peripheral: LPI2C1, signal: SDA, pin_signal: GPIO_SD_B1_05, identifier: I2C1_SDA}
  - {pin_num: J14, peripheral: CSI, signal: 'csi_data, 02', pin_signal: GPIO_AD_B1_15}
  - {pin_num: G12, peripheral: CSI, signal: 'csi_data, 03', pin_signal: GPIO_AD_B1_14}
  - {pin_num: H11, peripheral: CSI, signal: 'csi_data, 04', pin_signal: GPIO_AD_B1_13}
  - {pin_num: H12, peripheral: CSI, signal: 'csi_data, 05', pin_signal: GPIO_AD_B1_12}
  - {pin_num: J13, peripheral: CSI, signal: 'csi_data, 06', pin_signal: GPIO_AD_B1_11}
  - {pin_num: L13, peripheral: CSI, signal: 'csi_data, 07', pin_signal: GPIO_AD_B1_10}
  - {pin_num: M13, peripheral: CSI, signal: 'csi_data, 08', pin_signal: GPIO_AD_B1_09}
  - {pin_num: H13, peripheral: CSI, signal: 'csi_data, 09', pin_signal: GPIO_AD_B1_08}
  - {pin_num: K10, peripheral: CSI, signal: csi_hsync, pin_signal: GPIO_AD_B1_07}
  - {pin_num: J12, peripheral: CSI, signal: csi_vsync, pin_signal: GPIO_AD_B1_06}
  - {pin_num: K12, peripheral: CSI, signal: csi_mclk, pin_signal: GPIO_AD_B1_05}
  - {pin_num: L12, peripheral: CSI, signal: csi_pixclk, pin_signal: GPIO_AD_B1_04}
  - {pin_num: M12, peripheral: GPIO1, signal: 'gpio_io, 19', pin_signal: GPIO_AD_B1_03, direction: OUTPUT}
  - {pin_num: L11, peripheral: ADC1, signal: 'IN, 7', pin_signal: GPIO_AD_B1_02}
  - {pin_num: K11, peripheral: ADC2, signal: 'IN, 6', pin_signal: GPIO_AD_B1_01}
  - {pin_num: J11, peripheral: ADC1, signal: 'IN, 5', pin_signal: GPIO_AD_B1_00}
  - {pin_num: L10, peripheral: ADC1, signal: 'IN, 4', pin_signal: GPIO_AD_B0_15}
  - {pin_num: H14, peripheral: ADC1, signal: 'IN, 3', pin_signal: GPIO_AD_B0_14}
  - {pin_num: K14, peripheral: LPUART1, signal: TX, pin_signal: GPIO_AD_B0_12, identifier: UART1_TX}
  - {pin_num: L14, peripheral: LPUART1, signal: RX, pin_signal: GPIO_AD_B0_13, identifier: UART1_RX}
  - {pin_num: F12, peripheral: JTAG, signal: TCK, pin_signal: GPIO_AD_B0_07}
  - {pin_num: E14, peripheral: JTAG, signal: TMS, pin_signal: GPIO_AD_B0_06}
  - {pin_num: G14, peripheral: SRC, signal: 'BOOT_MODE, 1', pin_signal: GPIO_AD_B0_05}
  - {pin_num: F11, peripheral: SRC, signal: 'BOOT_MODE, 0', pin_signal: GPIO_AD_B0_04}
  - {pin_num: F13, peripheral: ENC1, signal: 'PHASE, A', pin_signal: GPIO_AD_B0_08, drive_strength: R0_4}
  - {pin_num: F14, peripheral: ENC1, signal: 'PHASE, B', pin_signal: GPIO_AD_B0_09, drive_strength: R0_4}
  - {pin_num: G10, peripheral: ENC2, signal: 'PHASE, A', pin_signal: GPIO_AD_B0_11, drive_strength: R0_4}
  - {pin_num: G13, peripheral: ENC2, signal: 'PHASE, B', pin_signal: GPIO_AD_B0_10, drive_strength: R0_4}
  - {pin_num: G11, peripheral: GPIO1, signal: 'gpio_io, 03', pin_signal: GPIO_AD_B0_03, direction: OUTPUT, gpio_init_state: 'true', drive_strength: R0_7}
  - {pin_num: M11, peripheral: GPIO1, signal: 'gpio_io, 02', pin_signal: GPIO_AD_B0_02, direction: OUTPUT, gpio_init_state: 'true', drive_strength: R0_7}
  - {pin_num: H10, peripheral: GPIO1, signal: 'gpio_io, 01', pin_signal: GPIO_AD_B0_01, direction: INPUT}
  - {pin_num: M14, peripheral: GPIO1, signal: 'gpio_io, 00', pin_signal: GPIO_AD_B0_00, direction: OUTPUT, gpio_init_state: 'true', drive_strength: R0_7}
  - {pin_num: B9, peripheral: PWM2, signal: 'A, 1', pin_signal: GPIO_B0_08, identifier: PWM2_A1, direction: OUTPUT}
  - {pin_num: A11, peripheral: AOI1, signal: 'OUT, 0', pin_signal: GPIO_B1_00, drive_strength: R0}
  - {pin_num: D11, peripheral: AOI1, signal: 'OUT, 1', pin_signal: GPIO_B1_03, drive_strength: R0}
  - {peripheral: AOI1, signal: 'IN, 0', pin_signal: ACMP1_OUT}
  - {peripheral: AOI1, signal: 'IN, 1', pin_signal: ACMP2_OUT}
  - {pin_num: L10, peripheral: CMP3, signal: 'IN, 2', pin_signal: GPIO_AD_B0_15, identifier: ''}
  - {pin_num: H14, peripheral: CMP2, signal: 'IN, 2', pin_signal: GPIO_AD_B0_14, identifier: ''}
  - {pin_num: J11, peripheral: CMP4, signal: 'IN, 2', pin_signal: GPIO_AD_B1_00, identifier: ''}
  - {pin_num: L11, peripheral: CMP1, signal: 'IN, 3', pin_signal: GPIO_AD_B1_02, identifier: ''}
  - {peripheral: CMP4, signal: SAMPLE, pin_signal: ACMP4_OUT}
  - {peripheral: CMP3, signal: SAMPLE, pin_signal: ACMP3_OUT}
  - {peripheral: CMP2, signal: SAMPLE, pin_signal: ACMP2_OUT}
  - {pin_num: N14, peripheral: CMP1, signal: DAC_6bit_VIN1, pin_signal: VDDA_ADC_3P3}
  - {pin_num: N14, peripheral: CMP1, signal: DAC_6bit_VIN2, pin_signal: VDDA_ADC_3P3}
  - {peripheral: AOI1, signal: 'IN, 4', pin_signal: ACMP3_OUT}
  - {peripheral: AOI1, signal: 'IN, 5', pin_signal: ACMP4_OUT}
  - {peripheral: CMP1, signal: SAMPLE, pin_signal: LOGIC_HIGH}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RTEPIN_AllPin
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void RTEPIN_AllPin(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           
  CLOCK_EnableClock(kCLOCK_Xbar1);            
  CLOCK_EnableClock(kCLOCK_Xbar2);            

  /* GPIO configuration of LED_BUSR on GPIO_AD_B0_00 (pin M14) */
  gpio_pin_config_t LED_BUSR_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 1U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_00 (pin M14) */
  GPIO_PinInit(GPIO1, 0U, &LED_BUSR_config);

  /* GPIO configuration of KEY_BTUS on GPIO_AD_B0_01 (pin H10) */
  gpio_pin_config_t KEY_BTUS_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_01 (pin H10) */
  GPIO_PinInit(GPIO1, 1U, &KEY_BTUS_config);

  /* GPIO configuration of LED_BUSG on GPIO_AD_B0_02 (pin M11) */
  gpio_pin_config_t LED_BUSG_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 1U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_02 (pin M11) */
  GPIO_PinInit(GPIO1, 2U, &LED_BUSG_config);

  /* GPIO configuration of LED_USR on GPIO_AD_B0_03 (pin G11) */
  gpio_pin_config_t LED_USR_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 1U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_03 (pin G11) */
  GPIO_PinInit(GPIO1, 3U, &LED_USR_config);

  /* GPIO configuration of CAM_RST on GPIO_AD_B1_03 (pin M12) */
  gpio_pin_config_t CAM_RST_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_03 (pin M12) */
  GPIO_PinInit(GPIO1, 19U, &CAM_RST_config);

  /* GPIO configuration of DISP_D_C on GPIO_B0_00 (pin D7) */
  gpio_pin_config_t DISP_D_C_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B0_00 (pin D7) */
  GPIO_PinInit(GPIO2, 0U, &DISP_D_C_config);

  /* GPIO configuration of DISP_BKL on GPIO_B0_01 (pin E7) */
  gpio_pin_config_t DISP_BKL_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B0_01 (pin E7) */
  GPIO_PinInit(GPIO2, 1U, &DISP_BKL_config);

  /* GPIO configuration of TOF1_INT on GPIO_B0_12 (pin C10) */
  gpio_pin_config_t TOF1_INT_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B0_12 (pin C10) */
  GPIO_PinInit(GPIO2, 12U, &TOF1_INT_config);

  /* GPIO configuration of TOF1_XHT on GPIO_B0_13 (pin D10) */
  gpio_pin_config_t TOF1_XHT_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B0_13 (pin D10) */
  GPIO_PinInit(GPIO2, 13U, &TOF1_XHT_config);

  /* GPIO configuration of TOF0_INT on GPIO_B0_14 (pin E10) */
  gpio_pin_config_t TOF0_INT_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B0_14 (pin E10) */
  GPIO_PinInit(GPIO2, 14U, &TOF0_INT_config);

  /* GPIO configuration of TOF0_XHT on GPIO_B0_15 (pin E11) */
  gpio_pin_config_t TOF0_XHT_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B0_15 (pin E11) */
  GPIO_PinInit(GPIO2, 15U, &TOF0_XHT_config);

  /* GPIO configuration of KEY_BTME on GPIO_B1_01 (pin B11) */
  gpio_pin_config_t KEY_BTME_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_01 (pin B11) */
  GPIO_PinInit(GPIO2, 17U, &KEY_BTME_config);

  /* GPIO configuration of MOTOR_EN on GPIO_B1_02 (pin C11) */
  gpio_pin_config_t MOTOR_EN_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_02 (pin C11) */
  GPIO_PinInit(GPIO2, 18U, &MOTOR_EN_config);

  /* GPIO configuration of KEY_BTSE on GPIO_B1_04 (pin E12) */
  gpio_pin_config_t KEY_BTSE_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_04 (pin E12) */
  GPIO_PinInit(GPIO2, 20U, &KEY_BTSE_config);

  /* GPIO configuration of SERVO_EN on GPIO_B1_05 (pin D12) */
  gpio_pin_config_t SERVO_EN_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_05 (pin D12) */
  GPIO_PinInit(GPIO2, 21U, &SERVO_EN_config);

  /* GPIO configuration of BEEP_EN on GPIO_B1_06 (pin C12) */
  gpio_pin_config_t BEEP_EN_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_06 (pin C12) */
  GPIO_PinInit(GPIO2, 22U, &BEEP_EN_config);

  /* GPIO configuration of KEY_BTDN on GPIO_B1_07 (pin B12) */
  gpio_pin_config_t KEY_BTDN_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_07 (pin B12) */
  GPIO_PinInit(GPIO2, 23U, &KEY_BTDN_config);

  /* GPIO configuration of KEY_BTRT on GPIO_B1_08 (pin A12) */
  gpio_pin_config_t KEY_BTRT_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_08 (pin A12) */
  GPIO_PinInit(GPIO2, 24U, &KEY_BTRT_config);

  /* GPIO configuration of KEY_BTLF on GPIO_B1_09 (pin A13) */
  gpio_pin_config_t KEY_BTLF_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_09 (pin A13) */
  GPIO_PinInit(GPIO2, 25U, &KEY_BTLF_config);

  /* GPIO configuration of KEY_BTOK on GPIO_B1_10 (pin B13) */
  gpio_pin_config_t KEY_BTOK_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_10 (pin B13) */
  GPIO_PinInit(GPIO2, 26U, &KEY_BTOK_config);

  /* GPIO configuration of KEY_BTUP on GPIO_B1_11 (pin C13) */
  gpio_pin_config_t KEY_BTUP_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_11 (pin C13) */
  GPIO_PinInit(GPIO2, 27U, &KEY_BTUP_config);

  /* GPIO configuration of TCS_INT on GPIO_SD_B1_02 (pin M3) */
  gpio_pin_config_t TCS_INT_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_SD_B1_02 (pin M3) */
  GPIO_PinInit(GPIO3, 2U, &TCS_INT_config);

  /* GPIO configuration of IMU_INT on GPIO_SD_B1_03 (pin M4) */
  gpio_pin_config_t IMU_INT_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_SD_B1_03 (pin M4) */
  GPIO_PinInit(GPIO3, 3U, &IMU_INT_config);

  /* GPIO configuration of DISP_RST on GPIO_EMC_41 (pin C7) */
  gpio_pin_config_t DISP_RST_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_41 (pin C7) */
  GPIO_PinInit(GPIO3, 27U, &DISP_RST_config);

  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_00_GPIO1_IO00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_01_GPIO1_IO01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_02_GPIO1_IO02, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_03_GPIO1_IO03, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_04_SRC_BOOT_MODE00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_05_SRC_BOOT_MODE01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_06_JTAG_TMS, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_07_JTAG_TCK, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_08_XBAR1_IN20, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_09_XBAR1_IN21, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_10_XBAR1_IN22, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_11_XBAR1_IN23, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_12_LPUART1_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_13_LPUART1_RX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_14_GPIO1_IO14, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_15_GPIO1_IO15, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_00_GPIO1_IO16, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_01_GPIO1_IO17, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_02_GPIO1_IO18, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_03_GPIO1_IO19, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_04_CSI_PIXCLK, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_05_CSI_MCLK, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_06_CSI_VSYNC, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_07_CSI_HSYNC, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_08_CSI_DATA09, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_09_CSI_DATA08, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_10_CSI_DATA07, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_11_CSI_DATA06, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_12_CSI_DATA05, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_13_CSI_DATA04, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_14_CSI_DATA03, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_15_CSI_DATA02, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_00_GPIO2_IO00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_01_GPIO2_IO01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_02_LPSPI4_SDO, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_03_LPSPI4_SCK, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_04_LPI2C2_SCL, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_05_LPI2C2_SDA, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_06_FLEXPWM2_PWMA00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_07_FLEXPWM2_PWMB00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_08_FLEXPWM2_PWMA01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_09_FLEXPWM2_PWMB01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_10_FLEXPWM2_PWMA02, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_11_FLEXPWM2_PWMB02, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_12_GPIO2_IO12, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_13_GPIO2_IO13, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_14_GPIO2_IO14, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_15_GPIO2_IO15, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_00_XBAR1_INOUT14, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_01_GPIO2_IO17, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_02_GPIO2_IO18, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_03_XBAR1_INOUT17, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_04_GPIO2_IO20, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_05_GPIO2_IO21, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_06_GPIO2_IO22, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_07_GPIO2_IO23, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_08_GPIO2_IO24, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_09_GPIO2_IO25, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_10_GPIO2_IO26, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_11_GPIO2_IO27, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_12_LPUART5_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_13_LPUART5_RX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_14_FLEXPWM4_PWMA02, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_15_FLEXPWM4_PWMA03, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_40_GPIO3_IO26, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_41_GPIO3_IO27, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_00_USDHC1_CMD, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_01_USDHC1_CLK, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_02_USDHC1_DATA0, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_03_USDHC1_DATA1, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_04_USDHC1_DATA2, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_05_USDHC1_DATA3, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_00_LPUART4_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_01_LPUART4_RX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_02_GPIO3_IO02, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_03_GPIO3_IO03, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_04_LPI2C1_SCL, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_05_LPI2C1_SDA, 0U); 
  IOMUXC_GPR->GPR6 = ((IOMUXC_GPR->GPR6 &
    (~(IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_14_MASK | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_17_MASK))) 
      | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_14(0x01U) 
      | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_17(0x01U) 
    );
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputLogicHigh, kXBARA1_OutputAcmp1Sample); 
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputAcmp2Out, kXBARA1_OutputAcmp2Sample); 
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputAcmp3Out, kXBARA1_OutputAcmp3Sample); 
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputAcmp4Out, kXBARA1_OutputAcmp4Sample); 
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputIomuxXbarIn20, kXBARA1_OutputEnc1PhaseAInput); 
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputIomuxXbarIn21, kXBARA1_OutputEnc1PhaseBInput); 
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputIomuxXbarIn23, kXBARA1_OutputEnc2PhaseAInput); 
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputIomuxXbarIn22, kXBARA1_OutputEnc2PhaseBInput); 
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputAoi1Out0, kXBARA1_OutputIomuxXbarInout14); 
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputAoi1Out1, kXBARA1_OutputIomuxXbarInout17); 
  XBARB_SetSignalsConnection(XBARB2, kXBARB2_InputAcmp1Out, kXBARB2_OutputAoi1In00); 
  XBARB_SetSignalsConnection(XBARB2, kXBARB2_InputAcmp2Out, kXBARB2_OutputAoi1In01); 
  XBARB_SetSignalsConnection(XBARB2, kXBARB2_InputAcmp3Out, kXBARB2_OutputAoi1In04); 
  XBARB_SetSignalsConnection(XBARB2, kXBARB2_InputAcmp4Out, kXBARB2_OutputAoi1In05); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_00_GPIO1_IO00, 0x10B8U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_02_GPIO1_IO02, 0x10B8U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_03_GPIO1_IO03, 0x10B8U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_08_XBAR1_IN20, 0xB0A0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_09_XBAR1_IN21, 0x70A0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_10_XBAR1_IN22, 0x90A1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_11_XBAR1_IN23, 0x70A0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_00_GPIO2_IO00, 0x10B1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_01_GPIO2_IO01, 0x10B1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_02_LPSPI4_SDO, 0x10F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_03_LPSPI4_SCK, 0x10F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_00_XBAR1_INOUT14, 0x1088U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_01_GPIO2_IO17, 0x01F0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_02_GPIO2_IO18, 0x1088U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_03_XBAR1_INOUT17, 0x1088U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_04_GPIO2_IO20, 0x01F0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_05_GPIO2_IO21, 0x1088U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_07_GPIO2_IO23, 0x01F0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_08_GPIO2_IO24, 0x01F0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_09_GPIO2_IO25, 0x01F0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_10_GPIO2_IO26, 0x01F0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_11_GPIO2_IO27, 0x01F0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_12_LPUART5_TX, 0x10B1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_13_LPUART5_RX, 0x10B1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_41_GPIO3_IO27, 0x10B1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_00_USDHC1_CMD, 0x10B1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_01_USDHC1_CLK, 0x10B1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_02_USDHC1_DATA0, 0x10B1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_03_USDHC1_DATA1, 0x10B1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_04_USDHC1_DATA2, 0x10B1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B0_05_USDHC1_DATA3, 0x10B1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B1_00_LPUART4_TX, 0x10B1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B1_01_LPUART4_RX, 0x10B1U); 
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RTEPIN_Sdram:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: B7, peripheral: SEMC, signal: semc_dqs, pin_signal: GPIO_EMC_39, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: C2, peripheral: SEMC, signal: 'ADDR, 00', pin_signal: GPIO_EMC_09, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: G1, peripheral: SEMC, signal: 'ADDR, 01', pin_signal: GPIO_EMC_10, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: H1, peripheral: SEMC, signal: 'ADDR, 03', pin_signal: GPIO_EMC_12, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: A6, peripheral: SEMC, signal: 'ADDR, 04', pin_signal: GPIO_EMC_13, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: B6, peripheral: SEMC, signal: 'ADDR, 05', pin_signal: GPIO_EMC_14, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: A5, peripheral: SEMC, signal: 'ADDR, 07', pin_signal: GPIO_EMC_16, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: A4, peripheral: SEMC, signal: 'ADDR, 08', pin_signal: GPIO_EMC_17, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: B2, peripheral: SEMC, signal: 'ADDR, 09', pin_signal: GPIO_EMC_18, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: B4, peripheral: SEMC, signal: 'ADDR, 11', pin_signal: GPIO_EMC_19, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: G2, peripheral: SEMC, signal: 'ADDR, 10', pin_signal: GPIO_EMC_23, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: B1, peripheral: SEMC, signal: 'ADDR, 06', pin_signal: GPIO_EMC_15, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: G3, peripheral: SEMC, signal: 'ADDR, 02', pin_signal: GPIO_EMC_11, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: A3, peripheral: SEMC, signal: 'ADDR, 12', pin_signal: GPIO_EMC_20, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: C1, peripheral: SEMC, signal: 'BA, 0', pin_signal: GPIO_EMC_21, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: F1, peripheral: SEMC, signal: 'BA, 1', pin_signal: GPIO_EMC_22, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: D2, peripheral: SEMC, signal: semc_ras, pin_signal: GPIO_EMC_25, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: D3, peripheral: SEMC, signal: semc_cas, pin_signal: GPIO_EMC_24, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: D1, peripheral: SEMC, signal: semc_we, pin_signal: GPIO_EMC_28, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: E1, peripheral: SEMC, signal: 'CS, 0', pin_signal: GPIO_EMC_29, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: H3, peripheral: SEMC, signal: 'DM, 0', pin_signal: GPIO_EMC_08, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: D6, peripheral: SEMC, signal: 'DM, 1', pin_signal: GPIO_EMC_38, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: B3, peripheral: SEMC, signal: semc_clk, pin_signal: GPIO_EMC_26, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: A2, peripheral: SEMC, signal: semc_cke, pin_signal: GPIO_EMC_27, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: E3, peripheral: SEMC, signal: 'DATA, 00', pin_signal: GPIO_EMC_00, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: F3, peripheral: SEMC, signal: 'DATA, 01', pin_signal: GPIO_EMC_01, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: F4, peripheral: SEMC, signal: 'DATA, 02', pin_signal: GPIO_EMC_02, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: G4, peripheral: SEMC, signal: 'DATA, 03', pin_signal: GPIO_EMC_03, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: F2, peripheral: SEMC, signal: 'DATA, 04', pin_signal: GPIO_EMC_04, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: G5, peripheral: SEMC, signal: 'DATA, 05', pin_signal: GPIO_EMC_05, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: H5, peripheral: SEMC, signal: 'DATA, 06', pin_signal: GPIO_EMC_06, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: H4, peripheral: SEMC, signal: 'DATA, 07', pin_signal: GPIO_EMC_07, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: C6, peripheral: SEMC, signal: 'DATA, 08', pin_signal: GPIO_EMC_30, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: C5, peripheral: SEMC, signal: 'DATA, 09', pin_signal: GPIO_EMC_31, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: D5, peripheral: SEMC, signal: 'DATA, 10', pin_signal: GPIO_EMC_32, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: C4, peripheral: SEMC, signal: 'DATA, 11', pin_signal: GPIO_EMC_33, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: D4, peripheral: SEMC, signal: 'DATA, 12', pin_signal: GPIO_EMC_34, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: E5, peripheral: SEMC, signal: 'DATA, 13', pin_signal: GPIO_EMC_35, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: C3, peripheral: SEMC, signal: 'DATA, 14', pin_signal: GPIO_EMC_36, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: E4, peripheral: SEMC, signal: 'DATA, 15', pin_signal: GPIO_EMC_37, hysteresis_enable: Enable, speed: MHZ_200, slew_rate: Fast}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RTEPIN_Sdram
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void RTEPIN_Sdram(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_00_SEMC_DATA00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_01_SEMC_DATA01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_02_SEMC_DATA02, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_03_SEMC_DATA03, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_04_SEMC_DATA04, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_05_SEMC_DATA05, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_06_SEMC_DATA06, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_07_SEMC_DATA07, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_08_SEMC_DM00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_09_SEMC_ADDR00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_10_SEMC_ADDR01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_11_SEMC_ADDR02, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_12_SEMC_ADDR03, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_13_SEMC_ADDR04, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_14_SEMC_ADDR05, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_15_SEMC_ADDR06, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_16_SEMC_ADDR07, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_17_SEMC_ADDR08, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_18_SEMC_ADDR09, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_19_SEMC_ADDR11, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_20_SEMC_ADDR12, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_21_SEMC_BA0, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_22_SEMC_BA1, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_23_SEMC_ADDR10, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_24_SEMC_CAS, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_25_SEMC_RAS, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_26_SEMC_CLK, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_27_SEMC_CKE, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_28_SEMC_WE, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_29_SEMC_CS0, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_30_SEMC_DATA08, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_31_SEMC_DATA09, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_32_SEMC_DATA10, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_33_SEMC_DATA11, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_34_SEMC_DATA12, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_35_SEMC_DATA13, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_36_SEMC_DATA14, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_37_SEMC_DATA15, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_38_SEMC_DM01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_39_SEMC_DQS, 0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_00_SEMC_DATA00, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_01_SEMC_DATA01, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_02_SEMC_DATA02, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_03_SEMC_DATA03, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_04_SEMC_DATA04, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_05_SEMC_DATA05, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_06_SEMC_DATA06, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_07_SEMC_DATA07, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_08_SEMC_DM00, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_09_SEMC_ADDR00, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_10_SEMC_ADDR01, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_11_SEMC_ADDR02, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_12_SEMC_ADDR03, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_13_SEMC_ADDR04, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_14_SEMC_ADDR05, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_15_SEMC_ADDR06, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_16_SEMC_ADDR07, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_17_SEMC_ADDR08, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_18_SEMC_ADDR09, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_19_SEMC_ADDR11, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_20_SEMC_ADDR12, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_21_SEMC_BA0, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_22_SEMC_BA1, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_23_SEMC_ADDR10, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_24_SEMC_CAS, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_25_SEMC_RAS, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_26_SEMC_CLK, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_27_SEMC_CKE, 0x0130F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_28_SEMC_WE, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_29_SEMC_CS0, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_30_SEMC_DATA08, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_31_SEMC_DATA09, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_32_SEMC_DATA10, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_33_SEMC_DATA11, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_34_SEMC_DATA12, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_35_SEMC_DATA13, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_36_SEMC_DATA14, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_37_SEMC_DATA15, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_38_SEMC_DM01, 0x0110F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_39_SEMC_DQS, 0x0110F1U); 
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RTEPIN_QspiFlash:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: L3, peripheral: FLEXSPI, signal: FLEXSPI_A_SS0_B, pin_signal: GPIO_SD_B1_06}
  - {pin_num: L4, peripheral: FLEXSPI, signal: FLEXSPI_A_SCLK, pin_signal: GPIO_SD_B1_07}
  - {pin_num: P3, peripheral: FLEXSPI, signal: FLEXSPI_A_DATA0, pin_signal: GPIO_SD_B1_08}
  - {pin_num: N4, peripheral: FLEXSPI, signal: FLEXSPI_A_DATA1, pin_signal: GPIO_SD_B1_09}
  - {pin_num: P4, peripheral: FLEXSPI, signal: FLEXSPI_A_DATA2, pin_signal: GPIO_SD_B1_10}
  - {pin_num: P5, peripheral: FLEXSPI, signal: FLEXSPI_A_DATA3, pin_signal: GPIO_SD_B1_11}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RTEPIN_QspiFlash
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void RTEPIN_QspiFlash(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_06_FLEXSPIA_SS0_B, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_07_FLEXSPIA_SCLK, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_08_FLEXSPIA_DATA00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_09_FLEXSPIA_DATA01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_10_FLEXSPIA_DATA02, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_11_FLEXSPIA_DATA03, 0U); 
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
